header
openworld-community/peredelano-landing pull request #18
Opened 2023-06-19 15:38 UTC by S-E-A-JS

Компонент Хедер

2023-06-19 16:09 UTC, wanku-x requested changes

2023-06-19 16:09 UTC, wanku-x commented on src/layout/Header/Header.module.css
> +	&__navItem {
Тут тоже

2023-06-19 16:09 UTC, wanku-x commented on src/layout/Header/Header.module.css
> +		color: var(--color-white);
Не нужно, ибо я сделал белый цвет глобально для всего документа

2023-06-19 16:09 UTC, wanku-x commented on src/layout/Header/Header.tsx
> +import Image from 'next/image'
Не, в пизду, не нужон он нам. Там все равно svg. Лишний компонент ток тянуть, который будет оптимизировать то, что и так оптимизированно ручками.

2023-06-19 16:09 UTC, wanku-x commented on src/layout/Header/Header.tsx
> +								запустить свой стартап
Напиши с заглавных буков и сделай lowercase для ссылок

2023-06-19 16:09 UTC, wanku-x commented on src/layout/index.ts
Тут экспорт забыл сделать

2023-06-19 16:21 UTC, wanku-x requested changes

2023-06-19 16:21 UTC, wanku-x commented on src/layout/Header/Header.module.css
> +	&__navList {
Еще ты забыл обнулить у списка margin сверху и снизу, а также padding слева

2023-06-19 16:21 UTC, wanku-x commented on src/layout/Header/Header.module.css
> +		@media (--md) {
Поменяй на `--lg`. На планшете не умещается и все разъебывает

2023-06-19 16:57 UTC, S-E-A-JS commented on public/images/logo/logo.svg
сделано

2023-06-19 16:58 UTC, S-E-A-JS commented on src/layout/Header/Header.module.css
> +		padding-left: var(--gap);
удалено

2023-06-19 17:15 UTC, S-E-A-JS commented on src/layout/Header/Header.tsx
> +import Image from 'next/image'
поменял на img

2023-06-19 17:44 UTC, S-E-A-JS commented on src/layout/Header/Header.tsx
> +								запустить свой стартап
есть

2023-06-19 17:45 UTC, S-E-A-JS commented on src/layout/index.ts
исправлено

2023-06-19 18:16 UTC, wanku-x requested changes

2023-06-19 18:16 UTC, wanku-x commented on src/layouts/Header/Header.tsx
> +						height={63}
width и height - это круто. Но в нашей дизайн системе они не работают. Лучше убрать

2023-06-19 18:16 UTC, wanku-x commented on src/layouts/Header/Header.tsx
> +									{name.toLowerCase()}
Лучше делать через стили, это дешевле: `text-transform: lowercase`

2023-06-19 18:16 UTC, wanku-x commented on src/layouts/Header/Header.module.css
> +	&__nav-item &__nav-link {
Коль у `&__nav-item` больше нет стилей, то он и нахуй не нужон. Вложенные селекторы тут не нужны, они только повышают специфичность. Лучше его отсюда удалить и удалить в разметке

2023-06-19 18:16 UTC, wanku-x commented on src/layouts/Header/Header.tsx
> +							<li className={styles['header__nav-item']} key={id}>
Вот тута удалить этот класс за ненадобностью

2023-06-19 18:19 UTC, wanku-x requested changes

2023-06-19 18:19 UTC, wanku-x commented on src/layouts/Header/Header.tsx
> +						height={63}
Тут width и height полезны были бы в другой дизайн системе. Тут они бесполезны и не нужны. Скорее наоборот будут мешать

2023-06-19 18:34 UTC, wanku-x commented on src/layouts/Header/Header.tsx
> +						height={63}
А, еще запустил в рантайме. Для логотипа нужно задать высоту в css. Попробуй 32--px забубенить

2023-06-20 19:43 UTC, wanku-x approved these changes

2023-06-20 19:43 UTC, merged